### ISSUE TITLE
No way to make system use HWE kernel as default boot option

### ISSUE THREAD

**Issue by ToddDTaft** [covertsh/ubuntu-autoinstall-generator#12]
I have a system that requires the HWE kernel to be running just to make it through the entire server install process.  There should be an option that will set the GRUB config to use this mode during the install as the default option.

**Comment by covertsh** [comment]
Hi, thanks for your report. This is a pretty simple option to add and I can definitely understand the use case. I will work on this as soon as I have some free time, hopefully this weekend.

**Comment by covertsh** [comment]
This has been added in the latest version of the script.
