### ISSUE TITLE
boot gets stuck at subiquity/Mirro/lookup:cancelled

### ISSUE THREAD

**Issue by an0wak** [covertsh/ubuntu-autoinstall-generator#18]
Hi,
May I say awesome script - saves a hell of a lot of time! Unfortunately I can't get it to work and not sure why?

If I run the basic script with -a -c -k using ubuntu example user-data, I get nowhere.

![error](https://user-images.githubusercontent.com/74270857/130009737-1d005d2b-0ee1-44ea-9df1-31fdedbc9511.png)

If I open a second session to that system I can see something about CDrom not mounting
![error2](https://user-images.githubusercontent.com/74270857/130009812-bedf7ec5-76b3-4900-a9e2-e80835b406ab.png)

What am I missing?

**Comment by covertsh** [comment]
Hi, thank you for opening an issue. I can see from the second screenshot that the system is connected to a network during the install. Does that network provide an internet connection?
May I also ask which hypervisor you are using for this VM?

**Comment by covertsh** [comment]
I have run the script in a clean test environment as follows:
```bash ubuntu-autoinstall-generator.sh -a -u user-data.example -k -c```
I was able to boot the generated ISO in Hyper-V and the installation completed as expected, resulting in a working Ubuntu VM. It seems I cannot replicate your issue right now but if you provide the details requested above, hopefully we can track down the problem and fix it for you.

**Comment by an0wak** [comment]
Hi Covertsh,

I was running this in KVM. After scratching my head for some time I deployed it under VMware and it worked, and since then onto production systems - so nothing to do with the script or process.. Now I'll just need to workout my KVM setup.

This script has saved me plenty of time! appreciate your work! 
You may close this ticket.

Kind Regards
