### ISSUE TITLE
-e parameter

### ISSUE THREAD

**Issue by Hamsterman** [covertsh/ubuntu-autoinstall-generator#2]
As far as I can tell the iso creation does not support -e parameter.

**Comment by covertsh** [comment]
Hi there. What version of mkisofs are you using, and what operating system version are you running on?

**Comment by Hamsterman** [comment]
I was trying to do this on Windows where it gave an error.
I then just googled mkisofs and found this: https://linux.die.net/man/8/mkisofs

I guess the windows version is different from the version you are using.
