### ISSUE TITLE
Simple thank you

### ISSUE THREAD

**Issue by robinkruyt** [covertsh/ubuntu-autoinstall-generator#7]
Just wanted to leave a quick thank you for creating this script. I've been trying to figure out how to setup a headless ubuntu server for a few days now, until I found this repo.

It worked on the first try and probably saved me a lot of time as I don't have to manually set boot options and stuff on a server that doesn't have a monitor.

**Comment by covertsh** [comment]
Thank you for your kind words, they are much appreciated. I'm glad this tool was able to help you.
